import styles from "../../../../../styles/movie-info.module.scss";
import { getMovie } from "../../../components/movie-info";
import { Iparams } from "../page";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: {
//     template: "%s | Next.js",
//     default: "Next.js",
//   },
//   description: "Generated by Next.js",
// };

export default async function RootLayout(
  {
    children,
    params: { id }
  }
) {
  const movie = await getMovie(id);

  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <img
            src={movie.poster_path}
            alt={movie.title}
            className={styles.poster}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
